package com.ilsecondodasinistra.catchit.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table calendar_dates.
 */
public class calendarDates implements java.io.Serializable {

    private Integer service_id;
    private String date;
    private Integer exception_type;

    public calendarDates() {
    }

    public calendarDates(Integer service_id, String date, Integer exception_type) {
        this.service_id = service_id;
        this.date = date;
        this.exception_type = exception_type;
    }

    public Integer getService_id() {
        return service_id;
    }

    public void setService_id(Integer service_id) {
        this.service_id = service_id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getException_type() {
        return exception_type;
    }

    public void setException_type(Integer exception_type) {
        this.exception_type = exception_type;
    }

}
