package com.ilsecondodasinistra.catchit.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table stop_times.
 */
public class stopTimes implements java.io.Serializable {

    private Integer trip_id;
    /** Not-null value. */
    private String arrival_time;
    /** Not-null value. */
    private String departure_time;
    private Integer stop_id;
    private int stop_sequence;
    private String stop_headsign;
    private Integer pickup_type;
    private Integer drop_off_type;
    private Float shape_dist_traveled;

    public stopTimes() {
    }

    public stopTimes(int stop_sequence) {
        this.stop_sequence = stop_sequence;
    }

    public stopTimes(Integer trip_id, String arrival_time, String departure_time, Integer stop_id, int stop_sequence, String stop_headsign, Integer pickup_type, Integer drop_off_type, Float shape_dist_traveled) {
        this.trip_id = trip_id;
        this.arrival_time = arrival_time;
        this.departure_time = departure_time;
        this.stop_id = stop_id;
        this.stop_sequence = stop_sequence;
        this.stop_headsign = stop_headsign;
        this.pickup_type = pickup_type;
        this.drop_off_type = drop_off_type;
        this.shape_dist_traveled = shape_dist_traveled;
    }

    public Integer getTrip_id() {
        return trip_id;
    }

    public void setTrip_id(Integer trip_id) {
        this.trip_id = trip_id;
    }

    /** Not-null value. */
    public String getArrival_time() {
        return arrival_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setArrival_time(String arrival_time) {
        this.arrival_time = arrival_time;
    }

    /** Not-null value. */
    public String getDeparture_time() {
        return departure_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeparture_time(String departure_time) {
        this.departure_time = departure_time;
    }

    public Integer getStop_id() {
        return stop_id;
    }

    public void setStop_id(Integer stop_id) {
        this.stop_id = stop_id;
    }

    public int getStop_sequence() {
        return stop_sequence;
    }

    public void setStop_sequence(int stop_sequence) {
        this.stop_sequence = stop_sequence;
    }

    public String getStop_headsign() {
        return stop_headsign;
    }

    public void setStop_headsign(String stop_headsign) {
        this.stop_headsign = stop_headsign;
    }

    public Integer getPickup_type() {
        return pickup_type;
    }

    public void setPickup_type(Integer pickup_type) {
        this.pickup_type = pickup_type;
    }

    public Integer getDrop_off_type() {
        return drop_off_type;
    }

    public void setDrop_off_type(Integer drop_off_type) {
        this.drop_off_type = drop_off_type;
    }

    public Float getShape_dist_traveled() {
        return shape_dist_traveled;
    }

    public void setShape_dist_traveled(Float shape_dist_traveled) {
        this.shape_dist_traveled = shape_dist_traveled;
    }

}
