package com.ilsecondodasinistra.catchit.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.ilsecondodasinistra.catchit.database.tripsDao;
import com.ilsecondodasinistra.catchit.database.stopsDao;
import com.ilsecondodasinistra.catchit.database.stopTimesDao;
import com.ilsecondodasinistra.catchit.database.routesDao;
import com.ilsecondodasinistra.catchit.database.calendarDatesDao;
import com.ilsecondodasinistra.catchit.database.calendarDao;
import com.ilsecondodasinistra.catchit.database.agencyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        tripsDao.createTable(db, ifNotExists);
        stopsDao.createTable(db, ifNotExists);
        stopTimesDao.createTable(db, ifNotExists);
        routesDao.createTable(db, ifNotExists);
        calendarDatesDao.createTable(db, ifNotExists);
        calendarDao.createTable(db, ifNotExists);
        agencyDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        tripsDao.dropTable(db, ifExists);
        stopsDao.dropTable(db, ifExists);
        stopTimesDao.dropTable(db, ifExists);
        routesDao.dropTable(db, ifExists);
        calendarDatesDao.dropTable(db, ifExists);
        calendarDao.dropTable(db, ifExists);
        agencyDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(tripsDao.class);
        registerDaoClass(stopsDao.class);
        registerDaoClass(stopTimesDao.class);
        registerDaoClass(routesDao.class);
        registerDaoClass(calendarDatesDao.class);
        registerDaoClass(calendarDao.class);
        registerDaoClass(agencyDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
