package com.ilsecondodasinistra.catchit.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table trips.
 */
public class trips extends com.ilsecondodasinistra.catchit.classes.Supertrips  implements java.io.Serializable {

    private int route_id;
    private int service_id;
    private int trip_id;
    private String trip_headsign;
    private String trip_short_name;
    private Integer direction_id;
    private String block_id;
    private Integer shape_id;
    private Integer wheelchair_accessible;

    public trips() {
    }

    public trips(int trip_id) {
        this.trip_id = trip_id;
    }

    public trips(int route_id, int service_id, int trip_id, String trip_headsign, String trip_short_name, Integer direction_id, String block_id, Integer shape_id, Integer wheelchair_accessible) {
        this.route_id = route_id;
        this.service_id = service_id;
        this.trip_id = trip_id;
        this.trip_headsign = trip_headsign;
        this.trip_short_name = trip_short_name;
        this.direction_id = direction_id;
        this.block_id = block_id;
        this.shape_id = shape_id;
        this.wheelchair_accessible = wheelchair_accessible;
    }

    public int getRoute_id() {
        return route_id;
    }

    public void setRoute_id(int route_id) {
        this.route_id = route_id;
    }

    public int getService_id() {
        return service_id;
    }

    public void setService_id(int service_id) {
        this.service_id = service_id;
    }

    public int getTrip_id() {
        return trip_id;
    }

    public void setTrip_id(int trip_id) {
        this.trip_id = trip_id;
    }

    public String getTrip_headsign() {
        return trip_headsign;
    }

    public void setTrip_headsign(String trip_headsign) {
        this.trip_headsign = trip_headsign;
    }

    public String getTrip_short_name() {
        return trip_short_name;
    }

    public void setTrip_short_name(String trip_short_name) {
        this.trip_short_name = trip_short_name;
    }

    public Integer getDirection_id() {
        return direction_id;
    }

    public void setDirection_id(Integer direction_id) {
        this.direction_id = direction_id;
    }

    public String getBlock_id() {
        return block_id;
    }

    public void setBlock_id(String block_id) {
        this.block_id = block_id;
    }

    public Integer getShape_id() {
        return shape_id;
    }

    public void setShape_id(Integer shape_id) {
        this.shape_id = shape_id;
    }

    public Integer getWheelchair_accessible() {
        return wheelchair_accessible;
    }

    public void setWheelchair_accessible(Integer wheelchair_accessible) {
        this.wheelchair_accessible = wheelchair_accessible;
    }

}
